from typing import Dict, Any, List, Optional, TypedDict
from dataclasses import dataclass
import subprocess
import os
import hashlib
from pathlib import Path


def _is_approved(script: str) -> bool:
    try:
        xdg_cache = os.environ.get("XDG_CACHE_HOME", os.path.expanduser("~/.cache"))
        cache_dir = Path(xdg_cache) / "vars-ng" / "approved_scripts"
        script_hash = hashlib.sha256(script.encode("utf-8")).hexdigest()
        return (cache_dir / script_hash).exists()
    except OSError:
        return False


def _approve(script: str) -> None:
    try:
        xdg_cache = os.environ.get("XDG_CACHE_HOME", os.path.expanduser("~/.cache"))
        cache_dir = Path(xdg_cache) / "vars-ng" / "approved_scripts"
        cache_dir.mkdir(parents=True, exist_ok=True)
        script_hash = hashlib.sha256(script.encode("utf-8")).hexdigest()
        (cache_dir / script_hash).touch()
    except OSError:
        pass


def _confirm_script(
    script: str, *, label: str, env_desc: str = "", args: str = ""
) -> None:
    if _is_approved(script):
        return
    print(f"\nAbout to run {label}:")
    if env_desc:
        print(f"  env: {env_desc}")
    print("  script:")
    for line in script.strip().split("\n"):
        print(f"    {line}")
    if args:
        print(f"  args: {args}")
    while True:
        try:
            resp = input("Proceed? [y/N]: ").strip().lower()
        except EOFError:
            print("Aborted.")
            exit(1)
        if resp == "y":
            _approve(script)
            return
        else:
            print("Aborted.")
            exit(1)


class FileConfig(TypedDict):
    """Represents the configuration for a single file generated by a generator."""

    deploy: bool
    generator: str
    group: str
    mode: str
    name: str
    owner: str
    path: Optional[str]
    secret: bool


class GeneratorConfig(TypedDict):
    """Represents the configuration for a generator, including its dependencies and output files."""

    dependencies: List[str]
    files: Dict[str, FileConfig]
    name: str
    prompts: Dict[str, Any]


class BackendConfig(TypedDict):
    name: str
    get: str
    set: str
    exists: str
    delete: Optional[str]
    list: Optional[str]
    generators: set[str]


class Backend:
    def __init__(self, name: str, config: BackendConfig):
        self.name = name
        self.config = config

    def get(
        self, *, gen_name: str, file_name: str, out_path: str, assume_yes: bool = False
    ) -> None:
        script = self.config["get"]
        if not assume_yes:
            _confirm_script(
                script,
                label=f"GET for {gen_name}/{file_name}",
                env_desc=f"out={out_path}",
                args=f"{gen_name} {file_name}",
            )
        subprocess.run(
            ["bash", "-c", script, "--", gen_name, file_name],
            env={"out": out_path, "PATH": os.environ.get("PATH", "")},
            check=True,
            capture_output=True,
        )

    def set(
        self, *, gen_name: str, file_name: str, in_path: str, assume_yes: bool = False
    ) -> None:
        script = self.config["set"]
        if not assume_yes:
            _confirm_script(
                script,
                label=f"SET for {gen_name}/{file_name}",
                env_desc=f"in={in_path}",
                args=f"{gen_name} {file_name}",
            )
        subprocess.run(
            ["bash", "-c", script, "--", gen_name, file_name],
            env={"in": in_path, "PATH": os.environ.get("PATH", "")},
            check=True,
            capture_output=True,
        )

    def exists(self, *, gen_name: str, file_name: str) -> bool:
        result = subprocess.run(
            ["bash", "-c", self.config["exists"], "--", gen_name, file_name],
            capture_output=True,
        )
        return result.returncode == 0

    def list(self) -> List[str]:
        if not self.config.get("list"):
            return []
        result = subprocess.run(
            ["bash", "-c", self.config["list"]],
            capture_output=True,
            text=True,
            check=True,
        )
        return [line for line in result.stdout.strip().split("\n") if line]

    def delete(
        self, *, gen_name: str, file_name: str, assume_yes: bool = False
    ) -> None:
        if not self.config.get("delete"):
            return
        script = self.config["delete"]
        if not assume_yes:
            _confirm_script(
                script,
                label=f"DELETE for {gen_name}/{file_name}",
                args=f"{gen_name} {file_name}",
            )
        subprocess.run(
            ["bash", "-c", script, "--", gen_name, file_name],
            check=True,
            capture_output=True,
            text=True,
        )


@dataclass
class VarsConfig:
    generators: Dict[str, GeneratorConfig]
    backends: Dict[str, Backend]
    gen_to_backend: Dict[str, str]
