from typing import Dict, Any, List, Optional, TypedDict
from dataclasses import dataclass
import subprocess
import os


class FileConfig(TypedDict):
    """Represents the configuration for a single file generated by a generator."""

    deploy: bool
    generator: str
    group: str
    mode: str
    name: str
    owner: str
    path: Optional[str]
    secret: bool


class GeneratorConfig(TypedDict):
    """Represents the configuration for a generator, including its dependencies, output files, and script."""

    dependencies: List[str]
    files: Dict[str, FileConfig]
    name: str
    prompts: Dict[str, Any]
    runtimeInputs: List[str]
    script: str


class BackendConfig(TypedDict):
    name: str
    get: str
    set: str
    exists: str
    delete: Optional[str]
    list: Optional[str]
    generators: set[str]


class Backend:
    def __init__(self, name: str, config: BackendConfig):
        self.name = name
        self.config = config

    def get(self, *, gen_name: str, file_name: str, out_path: str) -> None:
        subprocess.run(
            ["bash", "-c", self.config["get"], "--", gen_name, file_name],
            env={"out": out_path, "PATH": os.environ.get("PATH", "")},
            check=True,
            capture_output=True,
        )

    def set(self, *, gen_name: str, file_name: str, in_path: str) -> None:
        subprocess.run(
            ["bash", "-c", self.config["set"], "--", gen_name, file_name],
            env={"in": in_path, "PATH": os.environ.get("PATH", "")},
            check=True,
            capture_output=True,
        )

    def exists(self, *, gen_name: str, file_name: str) -> bool:
        result = subprocess.run(
            ["bash", "-c", self.config["exists"], "--", gen_name, file_name],
            capture_output=True,
        )
        return result.returncode == 0

    def list(self) -> List[str]:
        if not self.config.get("list"):
            return []
        result = subprocess.run(
            ["bash", "-c", self.config["list"]],
            capture_output=True,
            text=True,
            check=True,
        )
        return [line for line in result.stdout.strip().split("\n") if line]

    def delete(self, *, gen_name: str, file_name: str) -> None:
        if not self.config.get("delete"):
            return
        subprocess.run(
            ["bash", "-c", self.config["delete"], "--", gen_name, file_name],
            check=True,
            capture_output=True,
            text=True,
        )


@dataclass
class VarsConfig:
    generators: Dict[str, GeneratorConfig]
    backends: Dict[str, Backend]
    gen_to_backend: Dict[str, str]
