import argparse
import subprocess
import json
import os
import shutil
import tempfile
from pathlib import Path
from typing import Dict, Any, List, Tuple, Optional, TypedDict
from graphlib import TopologicalSorter

class FileConfig(TypedDict):
    """ Represents the configuration for a single file generated by a generator.
    """
    deploy: bool
    generator: str
    group: str
    mode: str
    name: str
    owner: str
    path: Optional[str]
    secret: bool

class GeneratorConfig(TypedDict):
    """ Represents the configuration for a generator, including its dependencies, output files, and script.
    """
    dependencies: List[str]
    files: Dict[str, FileConfig]
    name: str
    prompts: Dict[str, Any]
    runtimeInputs: List[str]
    script: str

def nix_instantiate(expr: str) -> Any:
    """ Evaluates a nix expression using nix-instantiate and returns the result as a Python object.
    """
    try:
        result = subprocess.run(
            ["nix-instantiate", "--eval", "--json", "--strict", "-E", expr],
            capture_output=True,
            text=True,
            check=True
        )
        return json.loads(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Error evaluating nix expression:\n{e.stderr}")
        exit(1)

def evaluate_config(config_nix: str, nixpkgs_path: Optional[str] = None) -> Dict[str, GeneratorConfig]:
    """ Evaluates the given config.nix file and returns a dictionary of generator configurations.
    """
    options_nix_path = Path(__file__).parent / "options.nix"
    config_nix = Path(config_nix).resolve().as_posix() # canonicalize

    nixpkgs_path = nixpkgs_path or "<nixpkgs>"

    nix_expr = f"""
let
  pkgs = import {nixpkgs_path} {{}};
in
(pkgs.lib.evalModules {{
  modules = [
    {{ _module.args.pkgs = pkgs; }}
    {options_nix_path}
    {config_nix}
  ];
}}).config.vars.generators
"""
    return nix_instantiate(nix_expr)

def get_sorted_generators(generators: Dict[str, GeneratorConfig]) -> List[str]:
    """ Returns a list of generator names sorted in topological order based on their dependencies. """
    ts = TopologicalSorter()
    for name, gen in generators.items():
        deps = gen["dependencies"]
        ts.add(name, *deps)
    try:
        return list(ts.static_order())
    except Exception as e:
        print(f"Error: Dependency cycle detected in configuration:\n{e}")
        exit(1)

def get_file_dest_path(output_dir: str, file_config: FileConfig) -> Path:
    """ Determines the destination path for a generated file based on its configuration. """
    visibility = "secret" if file_config["secret"] else "public"
    generator_name = file_config["generator"]
    name = file_config["name"]
    return Path(output_dir) / visibility / generator_name / name

def run_generator(gen_name: str, gen: GeneratorConfig, generators: Dict[str, GeneratorConfig], output_dir: str) -> None:
    """ Runs the specified generator, ensuring that its dependencies are available in the input directory and that the generated files are moved to their correct destinations with appropriate permissions. """
    old_umask = os.umask(0o077)
    try:
        with tempfile.TemporaryDirectory() as temp_dir_str:
            temp_dir = Path(temp_dir_str)
            in_dir = temp_dir / "in"
            out_dir = temp_dir / "out"
            in_dir.mkdir()
            out_dir.mkdir()

            # Set up inputs from dependencies
            for dep_name in gen["dependencies"]:
                dep_gen = generators[dep_name]
                dep_dir = in_dir / dep_name
                dep_dir.mkdir(exist_ok=True)
                for file_name, file_config in dep_gen["files"].items():
                    src_path = get_file_dest_path(output_dir, file_config)
                    dest_path = dep_dir / file_config["name"]
                    if src_path.exists():
                        shutil.copy2(src_path, dest_path)

            # Prepare environment
            env = os.environ.copy()
            env["in"] = str(in_dir)
            env["out"] = str(out_dir)

            # Prepare PATH with runtimeInputs
            runtime_inputs = gen["runtimeInputs"]
            bin_paths = [str(Path(p) / "bin") for p in runtime_inputs]
            if bin_paths:
                # Add existing PATH so standard tools (like bash itself, if not in runtimeInputs) are still available
                env["PATH"] = ":".join(bin_paths) + ":" + env.get("PATH", "")

            # Write and execute script
            script_content = gen["script"]
            script_path = temp_dir / "script.sh"
            script_path.write_text(f"#!/usr/bin/env bash\nset -euo pipefail\numask 077\n{script_content}")
            script_path.chmod(script_path.stat().st_mode | 0o111)

            try:
                subprocess.run([str(script_path)], env=env, check=True, cwd=str(temp_dir))
            except subprocess.CalledProcessError as e:
                print(f"Error executing script for generator {gen_name}")
                exit(1)

            # Move generated files to destination
            for file_config in gen["files"].values():
                name = file_config["name"]
                dest_path = get_file_dest_path(output_dir, file_config)

                src_file = out_dir / name
                if src_file.exists():
                    dest_path.parent.mkdir(parents=True, exist_ok=True)
                    shutil.move(str(src_file), str(dest_path))

                    # Set mode
                    mode_str = file_config["mode"]
                    if mode_str:
                        try:
                            dest_path.chmod(int(mode_str, 8))
                        except ValueError:
                            print(f"Warning: Invalid mode '{mode_str}' for {name}")
    finally:
        os.umask(old_umask)

def generator_needs_run(gen: GeneratorConfig, output_dir: str, rebuilt: set[str]) -> bool:
    # If any dependency was rebuilt during this run, we must also run
    if any(dep in rebuilt for dep in gen["dependencies"]):
        return True

    for file_config in gen["files"].values():
        path = get_file_dest_path(output_dir, file_config)
        if not path.exists():
            return True
    return False

def handle_generate(args: argparse.Namespace) -> None:
    generators = evaluate_config(args.configuration, args.nixpkgs)
    sorted_generators = get_sorted_generators(generators)

    print("Execution order:")
    rebuilt = set()

    for gen_name in sorted_generators:
        gen = generators[gen_name]
        print(f"- {gen_name}")

        if not generator_needs_run(gen, args.output_dir, rebuilt):
            if args.dry_run:
                print(f"  -> Would skip (already exists)")
            else:
                print(f"  -> Skipping (already exists)")
            continue

        rebuilt.add(gen_name)
        if args.dry_run:
            for file_config in gen["files"].values():
                path = get_file_dest_path(args.output_dir, file_config)
                print(f"  -> Would create/update: {path}")
        else:
            run_generator(gen_name, gen, generators, args.output_dir)

def get_descendants(target: str, generators: Dict[str, GeneratorConfig]) -> set[str]:
    rev_graph: Dict[str, List[str]] = {name: [] for name in generators}
    for name, gen in generators.items():
        for dep in gen["dependencies"]:
            if dep in rev_graph:
                rev_graph[dep].append(name)
            else:
                rev_graph[dep] = [name]

    descendants = set()
    def dfs(n: str) -> None:
        for child in rev_graph.get(n, []):
            if child not in descendants:
                descendants.add(child)
                dfs(child)

    dfs(target)
    return descendants

def handle_regenerate(args: argparse.Namespace) -> None:
    generators = evaluate_config(args.configuration, args.nixpkgs)

    if args.target not in generators:
        print(f"Error: Target generator '{args.target}' not found in configuration.")
        exit(1)

    to_regenerate = get_descendants(args.target, generators)
    to_regenerate.add(args.target)

    print(f"Regenerating {args.target} and its dependents: {', '.join(to_regenerate)}")

    for gen_name in to_regenerate:
        gen = generators[gen_name]
        for file_name, file_config in gen["files"].items():
            path = get_file_dest_path(args.output_dir, file_config)
            if path.exists():
                if args.dry_run:
                    print(f"  -> Would delete: {path}")
                else:
                    print(f"  -> Deleting: {path}")
                    path.unlink()

    # Fall back to normal generate flow to rebuild the missing files
    handle_generate(args)

def handle_garbage_collect(args: argparse.Namespace) -> None:
    generators = evaluate_config(args.configuration, args.nixpkgs)
    output_dir = Path(args.output_dir)

    if not output_dir.exists() or not output_dir.is_dir():
        print(f"Output directory {output_dir} does not exist. Nothing to collect.")
        return

    # Collect all expected file paths
    expected_files = set()
    for gen in generators.values():
        for file_config in gen["files"].values():
            expected_files.add(get_file_dest_path(args.output_dir, file_config).resolve())

    # Find all actual files in the output directory
    files_deleted = 0
    dirs_deleted = 0
    
    # Walk bottom-up so we can delete empty directories after their files are removed
    for root, dirs, files in os.walk(output_dir, topdown=False):
        current_dir = Path(root)
        
        # Check files
        for file_name in files:
            file_path = current_dir / file_name
            if file_path.resolve() not in expected_files:
                if args.dry_run:
                    print(f"Would delete orphaned file: {file_path}")
                else:
                    print(f"Deleting orphaned file: {file_path}")
                    file_path.unlink()
                files_deleted += 1
                
        # Check directories (delete if empty)
        for dir_name in dirs:
            dir_path = current_dir / dir_name
            if dir_path.exists() and not any(dir_path.iterdir()):
                if args.dry_run:
                    print(f"Would delete empty directory: {dir_path}")
                else:
                    print(f"Deleting empty directory: {dir_path}")
                    dir_path.rmdir()
                dirs_deleted += 1

    if files_deleted == 0 and dirs_deleted == 0:
        print("No orphaned files or directories found.")
    else:
        action = "Would collect" if args.dry_run else "Collected"
        print(f"{action} {files_deleted} files and {dirs_deleted} directories.")

def handle_evaluate(args: argparse.Namespace) -> None:
    data = evaluate_config(args.configuration, args.nixpkgs)

    # Check for cycles
    get_sorted_generators(data)

    existing_files = []
    missing_files = []

    for gen in data.values():
        for file_config in gen["files"].values():
            path = get_file_dest_path(args.output_dir, file_config)
            if path.exists():
                existing_files.append(path)
            else:
                missing_files.append(path)

    if existing_files and missing_files:
        print("Note: Inconsistent state detected. Some generated files exist while others are missing.")
        print("You can run 'vars-ng generate' to fill in the missing files.")

    print(json.dumps(data, indent=2))

def main() -> None:
    parser = argparse.ArgumentParser(description="vars-ng CLI")
    
    # Global arguments
    parser.add_argument("--configuration", required="VARS_CONFIG" not in os.environ, default=os.environ.get("VARS_CONFIG"), help="Path to config.nix (required unless $VARS_CONFIG is set)")
    parser.add_argument("--nixpkgs", default=os.environ.get("VARS_NIXPKGS"), help="Path to nixpkgs tree (default: $VARS_NIXPKGS)")
    parser.add_argument("--output-dir", default=os.environ.get("VARS_OUTPUT_DIR", "./output"), help="Directory to output generated files (default: ./output or $VARS_OUTPUT_DIR)")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be done without executing")

    subparsers = parser.add_subparsers(dest="command", required=True)

    # generate subcommand
    generate_parser = subparsers.add_parser("generate", help="Generate missing configuration")

    # regenerate subcommand
    regenerate_parser = subparsers.add_parser("regenerate", help="Regenerate a specific target and its dependencies")
    regenerate_parser.add_argument("target", help="Name of the generator to regenerate")

    # garbage-collect subcommand
    gc_parser = subparsers.add_parser("garbage-collect", help="Delete all vars from the output directory that are not declared")

    # evaluate subcommand
    evaluate_parser = subparsers.add_parser("evaluate", help="Evaluate configuration")

    args = parser.parse_args()

    if args.command == "generate":
        handle_generate(args)
    elif args.command == "regenerate":
        handle_regenerate(args)
    elif args.command == "garbage-collect":
        handle_garbage_collect(args)
    elif args.command == "evaluate":
        handle_evaluate(args)

if __name__ == "__main__":
    main()
